[terminal]
shell = "/bin/zsh"

[window]
startup_mode = "Maximized"

[font]
normal.family = "SF Mono"
bold.family = "SF Mono"
italic.family = "SF Mono"
bold_italic.family = "SF Mono"

size = 16

[cursor]
style.blinking = "Never"
